apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: cart-management
  name: cart-management
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cart-management
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cart-management
    spec:
      containers:
      - image: mish524/shoppingcart:v2
        ports:
        - containerPort: 3000
        name: cart-management
        resources: {}